apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-ingressgateway-certs
  namespace: istio-system
spec:
  secretName: auth-ingressgateway-certs
  issuerRef:
    name: <<__cert_issuer__>>
    kind: ClusterIssuer
  commonName: <<__subdomain_auth__>>.<<__domain__>>
  dnsNames:
  - <<__subdomain_auth__>>.<<__domain__>>
