issuer: https://<<__subdomain_auth__>>.<<__domain__>>
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  http: 0.0.0.0:5556
logger:
  level: "debug"
  format: text
oauth2:
  skipApprovalScreen: true
expiry:
  signingKeys: "4h"
  idTokens: "1h"
enablePasswordDB: true
staticPasswords:
- email: user@kubeflow.org
  hash: $2y$12$4K/VkmDd1q1Orb3xAt82zu8gk7Ad6ReFR4LCP9UeYE90NLiN9Df72
  # https://github.com/dexidp/dex/pull/1601/commits
  # FIXME: Use hashFromEnv instead
  username: user
  userID: "15841185641784"
staticClients:
# https://github.com/dexidp/dex/pull/1664
- idEnv: CLIENT_ID
  redirectURIs:
  - https://<<__subdomain_dashboard__>>.<<__domain__>>/oauth2/callback
  name: 'Dex Login Application'
  secretEnv: CLIENT_SECRET
