apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- auth-certificate.yaml
- auth-gateway.yaml
- authorizationpolicy.yaml
- crds.yaml
- deployment.yaml
- service.yaml
- virtual-service.yaml

configMapGenerator:
- name: dex-config
  files:
  - config.yaml
generatorOptions:
  disableNameSuffixHash: true

images:
- name: ghcr.io/dexidp/dex
  newName: ghcr.io/dexidp/dex
  newTag: v2.28.1
