apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    email: <<__cert_manager.email__>>
    server: <<__cert_manager.server__>>
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
    # TODO 
