apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: aws-secret
spec:
  backendType: secretsManager
  roleArn: <SETUP_CONF.ROLE_ARN.ETERNAL_SECRETS.AWS>
  data:
    - key: <SETUP_CONF.EXTERNAL_SECRET_NAME.AWS.RDS_USERNAME>
      name: RDS_USERNAME
    - key: <SETUP_CONF.EXTERNAL_SECRET_NAME.AWS.RDS_PASSWORD>
      name: RDS_PASSWORD
    - key: <SETUP_CONF.EXTERNAL_SECRET_NAME.AWS.S3_ACCESS_KEY>
      name: S3_ACCESS_KEY
    - key: <SETUP_CONF.EXTERNAL_SECRET_NAME.AWS.S3_SECRET_KEY>
      name: S3_SECRET_KEY
