# TODO, if we want to replace the helm chart with this, then we have to manually set up the ServiceAccount and attach the appropriate role to it.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    spec:
      containers:
        - name: external-dns
          args:
            - --source=service
            - --source=ingress
            - --domain-filter=<<__domain__>>
            - --provider=aws
            - --policy=upsert-only
            - --aws-zone-type=public
            - --registry=txt
            - --txt-owner-id=my-identifier
