apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: auth-destination-rule
  namespace: istio-system
spec:
  host: keycloak.auth.svc.cluster.local
  trafficPolicy: # Apply to all ports
    tls:
      mode: SIMPLE
