apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: kubeflow
  namespace: auth
  labels:
    app: sso
spec:
  realm:
    id: "kubeflow"
    realm: "kubeflow"
    enabled: True
    displayName: "Kubeflow Realm"
  instanceSelector:
    matchLabels:
      app: sso
