apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
- ../base
- cluster-issuer.yaml
- certificate.yaml

patchesStrategicMerge:
- patches/service-account.yaml
- patches/deployment.yaml
