apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "WGrVuz/b5BuF+mMDLVIaIqumOXF4ZqEwcIZ9f7xeBBnPhzIu4hXrKCskSEiiLbKD\nN8wm/coLFUT9MDdtLfAVoGTE/hP7FdzISJRP8YOgSwUJw/lEadBbx87pq/YEVxrV\nxEvfYM5zuXFwKYfI4YWkk98D+f5WrVHDTzKBa+KQykA="
