apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <SETUP_CONF.GIT_REPO.URL>
    targetRevision: <SETUP_CONF.GIT_REPO.TARGET_REVISION>
    path: distribution/kubeflow/common/istio
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
