kind: ConfigMap
apiVersion: v1
metadata:
  name: mlflow-config
data:
  DB_NAME: <<conf.rds.db_name.mlflow.conf>>
  RDS_HOST: <<conf.rds.host.conf>>
  RDS_PORT: "<<conf.rds.port.conf>>"
  ARTIFACT_S3_BUCKET: <<conf.artifact_s3_bucket.conf>>
