apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: rds-secret
  namespace: mlflow
spec:
  backendType: secretsManager
  roleArn: <SETUP_CONF.ROLE_ARN.EXTERNAL_SECRETS.AWS>
  data:
    - key: << external_secret_name.mlflow.rds_username >>
      name: RDS_USERNAME
    - key: << external_secret_name.mlflow.rds_password >>
      name: RDS_PASSWORD
