# output "cluster_id" {
#   description = "EKS cluster ID."
#   value       = module.eks.cluster_id
# }

# output "cluster_endpoint" {
#   description = "Endpoint for EKS control plane."
#   value       = module.eks.cluster_endpoint
# }

# output "cluster_security_group_id" {
#   description = "Security group ids attached to the cluster control plane."
#   value       = module.eks.cluster_security_group_id
# }

# output "kubectl_config" {
#   description = "kubectl config as generated by the module."
#   value       = module.eks.kubeconfig
# }

# output "config_map_aws_auth" {
#   description = "A kubernetes configuration to authenticate to this EKS cluster."
#   value       = module.eks.config_map_aws_auth
# }

# output "worker_iam" {
#   description = "The worker IAM role name"
#   value = module.eks.worker_iam_role_name
# }


output "kubeflow_pipeline_user_access_key" {
  value = aws_iam_user.pipelines_user.name
}

output "kubeflow_pipeline_user_secret_key" {
  value = aws_iam_access_key.pipelines_user.secret
  sensitive = false
}

# ----- Output for argoflow configuration
output "argoflow_config" {
  value = <<CONFIG
<<__role_arn.cluster_autoscaler__>>=${aws_iam_policy.cluster-autoscaler-policy.arn}
<<__role_arn.loadbalancer_controller__>>=${aws_iam_policy.load-balancer-policy.arn}
<<__role_arn.external_dns__>>=${aws_iam_policy.ext_dns.arn}

<<__role_arn.oauth2_proxy__>>=arn:aws:iam::890123456789:role/my-cluster_oauth2-proxy_oauth2-prox
<<__role_arn.pipelines__>>=arn:aws:iam::890123456789:role/my-cluster_kubeflow_pipelines
<<__role_arn.cert_manager__>>=${aws_iam_policy.ext_dns.arn}
<<__role_arn.kube2iam_pipelines__>>=arn:aws:iam::890123456789:role/my-cluster_kubeflow_kube2iam_pipelines

<<__role_arn.external_secrets__>>=${aws_iam_policy.external-secrets.arn}
<<__role_arn.external_secrets.mlflow__>>=${aws_iam_policy.external-secrets.arn}
<<__role_arn.external_secrets.kubeflow__>>=${aws_iam_policy.external-secrets.arn}
<<__role_arn.external_secrets.argocd__>>=${aws_iam_policy.external-secrets.arn}
<<__role_arn.external_secrets.auth__>>=${aws_iam_policy.external-secrets.arn}
<<__role_arn.external_secrets.istio_system__>>=${aws_iam_policy.external-secrets.arn}
<<__external_secret_name.istio_system.auth_ca_cert__>>=${var.cluster_name}/istio-system/auth_ca_cert
<<__external_secret_name.istio_system.auth_cert__>>=${var.cluster_name}/istio-system/auth_cert
<<__external_secret_name.istio_system.auth_cert_pk__>>=${var.cluster_name}/istio-system/auth_cert_pk
<<__external_secret_name.istio_system.gateway_ca_cert__>>=${var.cluster_name}/istio-system/gateway_ca_cert
<<__external_secret_name.istio_system.gateway_cert__>>=${var.cluster_name}/istio-system/gateway_cert
<<__external_secret_name.istio_system.gateway_cert_pk__>>=${var.cluster_name}/istio-system/gateway_cert_pk
<<__external_secret_name.istio_system.monitoring_ca_cert__>>=${var.cluster_name}/istio-system/monitoring_ca_cert
<<__external_secret_name.istio_system.monitoring_cert__>>=${var.cluster_name}/istio-system/monitoring_cert
<<__external_secret_name.istio_system.monitoring_cert_pk__>>=${var.cluster_name}/istio-system/monitoring_cert_pk
<<__external_secret_name.mlflow.rds_username__>>=${var.cluster_name}/mlflow/rds_username
<<__external_secret_name.mlflow.rds_password__>>=${var.cluster_name}/mlflow/rds_password
<<__external_secret_name.kubeflow.rds_username__>>=${var.cluster_name}/kubeflow/rds_username
<<__external_secret_name.kubeflow.rds_password__>>=${var.cluster_name}/kubeflow/rds_password
<<__external_secret_name.kubeflow.s3_accesskey__>>=${var.cluster_name}/kubeflow/s3_accesskey
<<__external_secret_name.kubeflow.s3_secretkey__>>=${var.cluster_name}/kubeflow/s3_secretkey
<<__external_secret_name.git_repo.https_username__>>=${var.cluster_name}/argocd/https_username
<<__external_secret_name.git_repo.https_password__>>=${var.cluster_name}/argocd/https_password
<<__external_secret_name.auth.oidc_client_id__>>=${var.cluster_name}/auth/client_id
<<__external_secret_name.auth.oidc_client_secret__>>=${var.cluster_name}/auth/client_secret
<<__external_secret_name.auth.oidc_cookie_secret__>>=${var.cluster_name}/auth/cookie_secret

<<__git_repo.url__>>=${var.repo_url}
<<__git_repo.target_revision__>>=${var.target_revision}

<<__cluster_name__>>=${var.cluster_name}
<<__aws_region__>>=${var.aws_region}
<<__vpc_id__>>=${module.vpc.vpc_id}
<<__domain__>>=${var.hosted_dns_name}
<<__subdomain_dashboard__>>=kubeflow
<<__subdomain_serving__>>=serving
<<__subdomain_auth__>>=auth
<<__subdomain_grafana__>>=grafana
<<__subdomain_kiali__>>=kiali
<<__subdomain_kubecost__>>=kubecost
<<__route53.hosted_zone_id__>>=${data.aws_route53_zone.domain.zone_id}
<<__route53.hosted_zone_domain__>>=${var.hosted_dns_name}
<<__route53.hosted_zone_hostnames__>>=kubeflow.${var.hosted_dns_name}, serving.${var.hosted_dns_name}, argocd.${var.hosted_dns_name}, auth.${var.hosted_dns_name}, grafana.${var.hosted_dns_name}, kiali.${var.hosted_dns_name}, *.serving.${var.hosted_dns_name}
<<__cert_manager.email_domain__>>=${aws_acm_certificate.cert.domain_name}
<<__cert_manager.email_user__>>=name.surname
<<__cert_manager.server__>>=https://acme-staging-v02.api.letsencrypt.org/directory

<<__rds.db_name.cache__>>=cachedb
<<__rds.db_name.pipelines__>>=mlpipeline
<<__rds.db_name.metadata__>>=metadb
<<__rds.db_name.katib__>>=katib
<<__rds.db_name.mlflow__>>=mlflow
<<__rds.host__>>=${aws_db_instance.argoflow-db-instance.address}
<<__rds.port__>>=${aws_db_instance.argoflow-db-instance.port}

<<__s3.bucket.mlflow__>>=${aws_s3_bucket.argoflow_state_bucket.id}
<<__s3.bucket.pipelines__>>=${aws_s3_bucket.argoflow_state_bucket.id}
<<__s3.key_prefix.mlflow__>>=mlflow/experiments
<<__s3.key_prefix.pipelines__>>=pipelines/artifacts
<<__s3.path.pipelines__>>=pipelines

<<__aws_load_balancer.scheme__>>=internet-facing
<<__aws_load_balancer.name__>>=nlb-${var.cluster_name}
<<__aws_load_balancer.nlb_target_type__>>=instance

<<__oidc.issuer__>>=${module.eks.cluster_oidc_issuer_url}
<<__oidc.redis.connection_url__>>=redis://${aws_elasticache_cluster.oauth_cache.cache_nodes.0.address}:${aws_elasticache_cluster.oauth_cache.cache_nodes.0.port}
  CONFIG
}