apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: git-repo-secret
  namespace: argocd
spec:
  backendType: secretsManager
  roleArn: <<role_arn.external_secrets.git_repo>>
  data:
    - key: <<external_secret_name.git_repo.https_username>>
      name: HTTPS_USERNAME
    - key: <<external_secret_name.git_repo.https_password>>
      name: HTTPS_PASSWORD
