kind: ConfigMap
apiVersion: v1
metadata:
  name: katib-rds-config
  namespace: kubeflow
data:
  DB_NAME: <SETUP_CONF.RDS.DB_NAME.KATIB>
  RDS_HOST: <SETUP_CONF.RDS.HOST>
  RDS_PORT: "<SETUP_CONF.RDS.PORT>"