apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-ingressgateway-certs
  namespace: istio-system
spec:
  secretName: auth-ingressgateway-certs
  issuerRef:
    name: kubeflow-self-signing-issuer
    kind: ClusterIssuer
  commonName: <<__subdomain_auth__>>.<<__domain__>>
  dnsNames:
    - <<__subdomain_auth__>>.<<__domain__>>
