apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: auth-ingressgateway-certs
  namespace: istio-system
spec:
  backendType: secretsManager
  roleArn: <<__role_arn.external_secrets.istio_system__>>
  data:
    - key: <<__external_secret_name.istio_system.....__>>
      name: #TODO
    - key: <<__external_secret_name.istio_system.....__>>
      name: #TODO
