apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-example-com
  namespace: monitoring
spec:
  secretName: grafana-example-com
  issuerRef:
    name: <<__cert_issuer__>>
    kind: ClusterIssuer
  commonName: <<__subdomain_grafana__>>
  dnsNames:
  - <<__subdomain_grafana__>>
